server {
    listen 80;

    server_name localhost;

    # React (SPA)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # API → gateway
    location /auth/ {
        proxy_pass http://gateway-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /doc/ {
        proxy_pass http://gateway-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /log/ {
        proxy_pass http://gateway-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}