version: "3.8"

services:

  nginx:
    build: ./frontend
    container_name: nginx
    ports:
      - "9000:80"
    depends_on:
      - gateway-service

  gateway-service:
    build: ./backend/gateway-service
    container_name: gateway-service
    ports:
      - "8000:8000"
    environment:
      SERVER_PORT: 8000

      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: auth-service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://auth-service:8080
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/auth/**

      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: doc-service
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://doc-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: Path=/doc/**

      SPRING_CLOUD_GATEWAY_ROUTES_2_ID: log-service
      SPRING_CLOUD_GATEWAY_ROUTES_2_URI: http://log-service:8082
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0: Path=/log/**

      CORS_ALLOWED_ORIGINS: http://175.121.145.253:9000
    depends_on:
      - auth-service
      - doc-service
      - log-service

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    depends_on:
      - auth_postgres
      - kafka
    environment:
      SERVER_PORT: 8080

      SPRING_DATASOURCE_URL: ${AUTH_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS: "false"
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer

  doc-service:
    build: ./backend/doc-service
    container_name: doc-service
    depends_on:
      - doc_postgres
      - kafka
    environment:
      SERVER_PORT: 8081

      SPRING_DATASOURCE_URL: ${DOC_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS: "false"
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer

  log-service:
    build: ./backend/log-service
    container_name: log-service
    depends_on:
      - log_postgres
      - kafka
    environment:
      SERVER_PORT: 8082

      SPRING_DATASOURCE_URL: ${LOG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.springframework.kafka.support.serializer.JsonDeserializer
      SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_VALUE_DEFAULT_TYPE: com.project.log.dto.event.LogEventDto
      SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: "*"
      SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest

      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
      SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS: "false"

  auth_postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/auth-postgres:/var/lib/postgresql/data

  doc_postgres:
    image: postgres:15
    container_name: doc_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DOC_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./data/doc-postgres:/var/lib/postgresql/data

  log_postgres:
    image: postgres:15
    container_name: log_postgres
    restart: always
    environment:
      POSTGRES_DB: ${LOG_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./data/log-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./logstash:/usr/share/logstash/pipeline

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama