services:

  nginx:
    build: ./frontend
    container_name: nginx
    ports:
      - "9000:80"
    depends_on:
      - gateway-service

  gateway-service:
    build: ./backend/gateway-service
    container_name: gateway-service
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - auth-service
      - doc-service
      - log-service

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${AUTH_DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
      - kafka

  doc-service:
    build: ./backend/doc-service
    container_name: doc-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DOC_DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - doc-postgres
      - kafka

  log-service:
    build: ./backend/log-service
    container_name: log-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${LOG_DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - log-postgres
      - kafka

  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/auth-postgres:/var/lib/postgresql/data

  doc-postgres:
    image: postgres:15
    container_name: doc_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DOC_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/doc-postgres:/var/lib/postgresql/data

  log-postgres:
    image: postgres:15
    container_name: log_postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${LOG_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/log-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./logstash:/usr/share/logstash/pipeline

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama